version: "3.7"
services:
  stream_socket_server:
    build: "."
    restart: "always"
    ports:
      - 3001:3001
      - 9997:9997
    networks:
      - webrtc_local
    command: "node index.js"

networks:
  webrtc_local:
    driver: bridge