version: "3.7"
services:
  stream_socket_server:
    build: "."
    restart: "always"
    ports:
      - 4000:4000
      - 443:443
    command: "node index.js"
    volumes:
      - ../frontV2/data/certbot/conf/live/demo.quant-robotics.kz:/usr/src/app/certs